#! /bin/bash
echo "[ 1 / 1 ] Setting GNU binutils as system binary tools..." && \
for b in addr2line ar as c++filt dwp elfedit gprof nm objcopy objdump ranlib readelf size strings strip 
do
  rm -v         /usr/bin/$b
  ln -sv $b.gnu /usr/bin/$b
done                                          && \
echo "[ info  ] GNU Binutils  set as system default binary tools"
